# Generated by Django 3.1.3 on 2020-11-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0003_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='SiteID',
        ),
    ]
