# Generated by Django 3.1.5 on 2021-01-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0005_auto_20201202_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteid',
            name='SiteAddress',
            field=models.CharField(default='NOT SET', help_text='Enter the site street address', max_length=200),
        ),
        migrations.AddField(
            model_name='siteid',
            name='SiteCity',
            field=models.CharField(default='NOT SET', help_text='Enter the site city', max_length=200),
        ),
        migrations.AddField(
            model_name='siteid',
            name='SiteState',
            field=models.CharField(default='NOT SET', help_text='Enter the site state', max_length=200),
        ),
        migrations.AddField(
            model_name='siteid',
            name='SiteZipCode',
            field=models.CharField(default='NOT SET', help_text='Enther the site zip code', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteid',
            name='SiteName',
            field=models.CharField(default='NOT SET', help_text='Enter the site location or name', max_length=200),
        ),
    ]
