# Generated by Django 3.1.3 on 2021-03-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0007_siteid_sitetelephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperinceSurveyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DecreasedPain', models.PositiveIntegerField(default=3, help_text='Decreased Pain')),
                ('DecreasedStress', models.PositiveBigIntegerField(default=3, help_text='Decreased Stress')),
                ('SessionUsefulness', models.PositiveBigIntegerField(default=3, help_text='Was the session useful')),
                ('SessionEnjoyability', models.PositiveBigIntegerField(default=3, help_text='Was the session enjoyable')),
                ('TechnologyFunction', models.PositiveBigIntegerField(default=3, help_text='Did the technology function properly')),
                ('ExperinceRecommendation', models.PositiveBigIntegerField(default=3, help_text='Would you reccomend this therapy')),
            ],
        ),
    ]
